# Be sure to customize TSAOptions.json BEFORE running this pipeline

trigger: none # We only want to trigger manually or based on resources
pr: none

schedules:
- cron: "0 2 * * 0,2,4" # At 02:00 on Sunday, Tuesday, and Thursday
  displayName: Periodic APIScan
  branches:
    include:
    - main

resources:
  repositories:
  - repository: MicroBuildTemplate
    type: git
    name: 1ESPipelineTemplates/MicroBuildTemplate
    ref: refs/tags/release
  pipelines:
  - pipeline: CI
    source: Library # TODO: This should match the name of your CI pipeline
    branch: main

extends:
  template: azure-pipelines/MicroBuild.1ES.Unofficial.yml@MicroBuildTemplate
  parameters:
    sdl:
      sourceAnalysisPool: VSEngSS-MicroBuild2022-1ES
    stages:
    - stage: scan
      displayName: APIScan
      jobs:
      - template: /azure-pipelines/apiscan_job.yml@self
        parameters:
          binarySource: CI
