trigger:
  batch: true
  branches:
    include:
    - main
    - microbuild
    - 'validate/*'
  paths:
    exclude:
    - doc/
    - '*.md'
    - .vscode/
    - azure-pipelines/release.yml
    - azure-pipelines/vs-insertion.yml
#schedules:
#- cron: "0 3 * * *" # Daily @ 8 PM PST
#  displayName: Daily vs-insertion
#  branches:
#    include:
#    - microbuild

parameters:
- name: RealSign
  displayName: Real sign?
  type: boolean
  default: false
# - name: ShouldSkipOptimize # Enable this and references to it below when setting EnableOptProf to true in build.yml.
#   displayName: Skip OptProf optimization
#   type: boolean
#   default: false
- name: EnableMacOSBuild
  displayName: Build on macOS
  type: boolean
  default: false # macOS is often bogged down in Azure Pipelines
- name: EnableLinuxBuild
  displayName: Build on linux
  type: boolean
  default: true
- name: RunTests
  displayName: Run tests
  type: boolean
  default: true
- name: EnableCompliance
  displayName: Run Compliance Tools
  type: boolean
  default: true
- name: EnableAPIScan
  displayName: Include APIScan with Compliance tools
  type: boolean
  default: false # enable in individual repos only AFTER updating TSAOptions.json with your own values

resources:
  repositories:
  - repository: MicroBuildTemplate
    type: git
    name: 1ESPipelineTemplates/MicroBuildTemplate
    ref: refs/tags/release

variables:
- template: GlobalVariables.yml

extends:
  ${{ if parameters.EnableCompliance }}:
    template: azure-pipelines/MicroBuild.1ES.Official.yml@MicroBuildTemplate
    parameters:
      sdl:
        sourceAnalysisPool: VSEngSS-MicroBuild2022-1ES
        policheck:
          enabled: true
          exclusionsFile: $(System.DefaultWorkingDirectory)\azure-pipelines\PoliCheckExclusions.xml
        suppression:
          suppressionFile: $(System.DefaultWorkingDirectory)\azure-pipelines\falsepositives.gdnsuppress
      stages:
      - stage: Build
        variables:
        - template: /azure-pipelines/BuildStageVariables.yml@self
        jobs:
        - template: /azure-pipelines/build.yml@self
          parameters:
            Is1ESPT: true
            RealSign: ${{ or(parameters.RealSign, eq(variables['Build.Reason'],'Schedule')) }}
            # ShouldSkipOptimize: ${{ parameters.ShouldSkipOptimize }}
            EnableCompliance: ${{ parameters.EnableCompliance }}
            EnableAPIScan: ${{ parameters.EnableAPIScan }}
            windowsPool: VSEngSS-MicroBuild2022-1ES
            linuxPool:
              name: AzurePipelines-EO
              demands:
              - ImageOverride -equals 1ESPT-Ubuntu22.04
              os: Linux
            macOSPool:
              name: Azure Pipelines
              vmImage: macOS-12
              os: macOS
            EnableMacOSBuild: ${{ parameters.EnableMacOSBuild }}
            EnableLinuxBuild: ${{ parameters.EnableLinuxBuild }}
            RunTests: ${{ parameters.RunTests }}
      - template: /azure-pipelines/prepare-insertion-stages.yml@self
        parameters:
          RealSign: ${{ or(parameters.RealSign, eq(variables['Build.Reason'],'Schedule')) }}
  ${{ else }}:
    template: azure-pipelines/MicroBuild.1ES.Unofficial.yml@MicroBuildTemplate
    parameters:
      sdl:
        sourceAnalysisPool: VSEngSS-MicroBuild2022-1ES
        suppression:
          suppressionFile: $(System.DefaultWorkingDirectory)\azure-pipelines\falsepositives.gdnsuppress
      stages:
      - stage: Build
        variables:
        - template: /azure-pipelines/BuildStageVariables.yml@self
        jobs:
        - template: /azure-pipelines/build.yml@self
          parameters:
            Is1ESPT: true
            RealSign: ${{ or(parameters.RealSign, eq(variables['Build.Reason'],'Schedule')) }}
            # ShouldSkipOptimize: ${{ parameters.ShouldSkipOptimize }}
            EnableCompliance: ${{ parameters.EnableCompliance }}
            EnableAPIScan: ${{ parameters.EnableAPIScan }}
            windowsPool: VSEngSS-MicroBuild2022-1ES
            linuxPool:
              name: AzurePipelines-EO
              demands:
              - ImageOverride -equals 1ESPT-Ubuntu22.04
              os: Linux
            macOSPool:
              name: Azure Pipelines
              vmImage: macOS-12
              os: macOS
            EnableMacOSBuild: ${{ parameters.EnableMacOSBuild }}
            EnableLinuxBuild: ${{ parameters.EnableLinuxBuild }}
            RunTests: ${{ parameters.RunTests }}
      - template: /azure-pipelines/prepare-insertion-stages.yml@self
        parameters:
          RealSign: ${{ or(parameters.RealSign, eq(variables['Build.Reason'],'Schedule')) }}
