parameters:
  includeMacOS:

steps:
- download: current
  artifact: coverageResults-Windows
  displayName: 🔻 Download Windows code coverage results
  continueOnError: true
- download: current
  artifact: coverageResults-Linux
  displayName: 🔻 Download Linux code coverage results
  continueOnError: true
- download: current
  artifact: coverageResults-macOS
  displayName: 🔻 Download macOS code coverage results
  continueOnError: true
  condition: ${{ parameters.includeMacOS }}
- powershell: |
    dotnet tool install --tool-path obj dotnet-coverage --version 17.3.2 --configfile azure-pipelines/justnugetorg.nuget.config
    obj/dotnet-coverage merge "$(Pipeline.Workspace)/*.cobertura.xml" -r -o obj/Cobertura.xml -f cobertura
  displayName: ⚙ Merge coverage
- task: PublishCodeCoverageResults@1
  displayName: 📢 Publish code coverage results to Azure DevOps
  inputs:
    codeCoverageTool: cobertura
    summaryFileLocation: obj/Cobertura.xml
    failIfCoverageEmpty: true
